// src/lib/components/hero.svelte
<header class="mx-auto mt-12 flex h-auto max-w-7xl items-center lg:mt-36">
	<div class="relative flex flex-col gap-8 lg:flex-row">
		<p
			class="z-10 max-w-6xl text-balance px-4 pt-0 text-center font-serif text-3xl leading-normal lg:px-0 lg:pt-32 lg:text-left lg:text-7xl"
		>
			A front-end developer with a passion for user experiences.
		</p>
		<img
			src="/images/patrick.jpg"
			alt=""
			class="right-0 top-0 aspect-square w-full self-end object-cover px-4 lg:absolute lg:-right-56 lg:w-1/2 lg:rounded-full lg:px-0"
		/>
	</div>
</header>

// src/components/Hero/Hero.tsx
import Image from "next/image";
import image from "@/images/000008510008.jpg";

function Hero() {
	return (
		<section className="flex flex-col gap-6 mt-16 mb-24 max-w-5xl mx-auto">
			<div className="flex flex-col gap-1 mx-auto max-w-6xl justify-start">
				<h2 className="text-2xl mb-4 font-bold max-w-4xl">
					A front-end developer with a passion for creating.
				</h2>
				<p className="text-s ml-12">
					A dedicated developer, trusted advisor, and passionate front-end specialist focused on
					creating accessible, high-performing, and user-friendly web experiences.
				</p>
			</div>
			<div className="relative mx-auto max-w-6xl w-full aspect-video max-h-[650px]">
				<Image
					alt=""
					src={image}
					fill
					className="rounded-2xl object-cover"
				/>
			</div>
		</section>
	);
}

export default Hero;
