// src/components/Hero/Hero.tsx
import Image from "next/image";
import image from "@/images/000008510008.jpg";

function Hero() {
	return (
		<section className="flex flex-col gap-6 mt-16 mb-24 max-w-5xl mx-auto">
			<div className="flex flex-col gap-1 mx-auto max-w-6xl justify-start">
				<h2 className="text-2xl mb-4 font-bold max-w-4xl">
					A front-end developer with a passion for creating.
				</h2>
				<p className="text-s ml-12">
					A dedicated developer, trusted advisor, and passionate front-end specialist focused on
					creating accessible, high-performing, and user-friendly web experiences.
				</p>
			</div>
			<div className="relative mx-auto max-w-6xl w-full aspect-video max-h-[650px]">
				<Image
					alt=""
					src={image}
					fill
					className="rounded-2xl object-cover"
				/>
			</div>
		</section>
	);
}

export default Hero;

// src/components/hero.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { gsap } from 'gsap';

	let image: HTMLImageElement;

	onMount(() => {
		window.addEventListener('mousemove', (e) => {
			const x = (window.innerWidth / 2 - e.clientX) / 90;
			const y = (window.innerHeight / 2 - e.clientY) / 90;

			gsap.to(image, {
				ease: 'power1.out',
				duration: 0.5,
				x: x,
				y: y
			});
		});
	});
</script>

<header
	class="relative mx-auto mb-[25vh] mt-16 flex h-[512px] max-w-7xl items-center justify-center xl:justify-start"
>
	<div class="flex flex-col gap-8 xl:flex-row">
		<p
			class="z-10 max-w-6xl text-balance px-4 pt-0 text-center font-serif text-3xl leading-normal xl:px-0 xl:text-left xl:text-7xl xl:leading-normal"
		>
			A front-end developer with a passion for user experiences.
		</p>
		<div
			class="right-0 top-0 mx-auto w-96 overflow-hidden bg-gradient-to-br from-hermes-200 to-hermes-300 xl:absolute xl:h-[512px] xl:w-[512px] xl:rounded-full"
		>
			<img src="/images/patrick.png" bind:this={image} alt="" />
		</div>
	</div>
</header>
