// apps/web/src/components/hero/hero.tsx
import { Image } from "@unpic/react";
import Scotch1 from "#/assets/18.png";
import Scotch2 from "#/assets/86.png";

interface HeroProps {
	title: string;
	image: {
		src: string;
		alt: string;
	};
}

function Hero(props: HeroProps) {
	const { title, image } = props;

	return (
		<section className="bg-black text-ginger">
			<div className="mx-auto pt-8 flex max-w-6xl flex-col gap-6 top-32 relative mb-32">
				<div className="mx-auto flex max-w-6xl flex-col justify-start gap-1">
					{title && <p className="text-l">{title}</p>}
				</div>

				{image && (
					<div className="relative mx-auto w-full max-w-6xl mt-6">
						<Image
							alt={image.alt}
							className="object-cover rounded-3xl aspect-video"
							height={650}
							src={image.src}
							width={1152}
						/>

						<Image
							className="absolute -right-14 -top-28 w-64"
							src={Scotch1}
							alt=""
							width={364}
							height={405}
						/>

						<Image
							className="absolute -left-16 -bottom-20 w-58"
							src={Scotch2}
							alt=""
							width={340}
							height={198}
						/>
					</div>
				)}
			</div>
		</section>
	);
}

export default Hero;

// src/lib/components/hero.component.svelte
<header class="mx-auto mt-12 flex h-auto max-w-7xl items-center lg:mt-36">
	<div class="relative flex flex-col gap-8 lg:flex-row">
		<p
			class="z-10 max-w-6xl text-balance px-4 pt-0 text-center font-serif text-3xl leading-normal lg:px-0 lg:pt-32 lg:text-left lg:text-7xl lg:leading-normal"
		>
			A front-end developer with a passion for user experiences.
		</p>
		<img
			src="/images/patrick.jpg"
			alt=""
			class="right-0 top-0 aspect-square w-full self-end object-cover px-4 lg:absolute lg:-right-56 lg:w-1/2 lg:rounded-full lg:px-0"
		/>
	</div>
</header>
