// src/patterns/navigation/navigation.tsx
import React, { type ReactElement } from 'react';
import Link, { type LinkProps } from 'next/link';
import Image, { type StaticImageData } from 'next/image';
import squiggly from '@/images/squiggly.svg';

function NavigationLink({
  children,
  ...props
}: LinkProps & { children: React.ReactNode }): ReactElement {
  return (
    <li className="text-base">
      <Link {...props}>{children}</Link>
    </li>
  );
}

interface NavigationProps {
  title: string;
}

export function Navigation({ title }: NavigationProps): ReactElement {
  return (
    <nav className="mx-auto mb-xs mt-xs flex max-w-screen-2xl justify-between px-md">
      <div className="flex w-full items-center justify-between">
        <Link
          href="/"
          className="group relative font-serif text-xl font-semibold"
        >
          <h1>
            {title}
            <span className="invisible absolute -bottom-3xs left-0 w-full opacity-0 transition-all duration-150 ease-in-out group-hover:visible group-hover:opacity-100">
              <Image src={squiggly as StaticImageData} alt="" />
            </span>
          </h1>
        </Link>

        <ul className="flex gap-sm">
          <NavigationLink href="#">Projects</NavigationLink>
          <NavigationLink href="#">Blog</NavigationLink>
          <NavigationLink href="#">Photography</NavigationLink>
          <NavigationLink href="#">Contact</NavigationLink>
        </ul>
      </div>
    </nav>
  );
}

// src/lib/components/navigation.svelte
<script>
	import gsap from 'gsap';
	import MenuIcon from '$lib/icons/menu.icon.svelte';
	import CloseIcon from '$lib/icons/close.icon.svelte';

	const items = [
		{ name: 'Home', href: '/' },
		{ name: 'Blog', href: '/' },
		{ name: 'About', href: '/' },
		{ name: 'Projects', href: '/' },
		{ name: 'Contact', href: '/' }
	];

	let menuOpen = false;

	const toggleMenu = () => (menuOpen = !menuOpen);

	const tweenIn = (node) => {
		let tl = gsap.timeline();

		tl.from(node, {
			duration: 1,
			opacity: 0,
			yPercent: -100,
			ease: 'power1.out'
		});

		tl.from('#navigation-close-button', {
			opacity: 0,
			duration: 0.5,
			ease: 'power1.out'
		});

		return {
			duration: 1000,
			tick: (t) => tl.progress(t)
		};
	};

	const tweenOut = (node) => {
		let tl = gsap.timeline();

		tl.to(node, {
			duration: 1,
			opacity: 0,
			yPercent: -100,
			ease: 'power1.out'
		});

		return {
			duration: 1000,
			tick: (t, u) => tl.progress(u)
		};
	};
</script>

<nav class="mx-auto flex w-full max-w-7xl">
	<button id="navigation-open-button" on:click={toggleMenu} class="flex items-center gap-2 p-4">
		<span class="min-w-12 font-bold uppercase">Menu</span>
		<MenuIcon class="w-8" />
	</button>

	{#if menuOpen}
		<div
			class="fixed left-0 top-0 z-50 flex h-full w-full flex-col backdrop-blur-lg backdrop-grayscale"
			in:tweenIn
			out:tweenOut
		>
			<div class="mx-auto w-full max-w-7xl">
				<button
					id="navigation-close-button"
					on:click={toggleMenu}
					class="flex items-center gap-2 p-4"
				>
					<span class="min-w-12 font-bold uppercase">Close</span>
					<CloseIcon class="relative -left-1 w-8" />
				</button>
			</div>
			<ul
				class="mx-auto mb-24 flex h-full w-full max-w-7xl flex-col justify-center gap-6 px-6 lg:gap-12"
			>
				{#each items as item, index}
					<li>
						<a href={item.href} class="group flex gap-4">
							<span class="text-lg">{index + 1}</span>
							<span
								class="font-serif text-4xl font-black transition-all duration-300 ease-in-out group-hover:font-light lg:text-8xl"
							>
								{item.name}
							</span>
						</a>
					</li>
				{/each}
			</ul>
		</div>
	{/if}
</nav>
